#! /bin/sh

bspc config 

source ~/.cache/wal/colors.sh
bspc config active_border_color $background
bspc config normal_border_color $background
bspc config focused_border_color $foreground

wal -R

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 

bspc config border_width        4

bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer     false

sxhkd &
polybar &

setxkbmap -option grp:alt_shift_toggle us,gr &

picom --config ~/.config/picom/picom.conf &

greenclip daemon &

xsetroot -cursor_name left_ptr &

nm-applet &

bash /home/kliogka/.config/bspwm/bspwm_colors.sh &

if xrandr | grep "HDMI1 connected"; then
    ~/.screenlayout/right-of-edp1.sh &
fi
